name: Mirror to GitHub

on:
  push:
    branches:
      - hosting-topology

jobs:
  mirror:
    name: Push to GitHub mirror
    runs-on: default
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitHub
        run: |
          git remote add github https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Maximum-ADD/sportsanalyticsMirror.git
          git push github hosting-topology
