import { cn } from "@/lib/utils";

const HERO_WIDTHS = [640, 960, 1440, 1920] as const;

function srcSetFor(extension: "avif" | "webp"): string {
  return HERO_WIDTHS.map((width) => `/hero-arena-${width}.${extension} ${width}w`).join(", ");
}

interface HeroPhotoProps {
  className?: string;
}

// Assets are generated by scripts/build-hero-assets.mjs.
export function HeroPhoto({ className }: HeroPhotoProps) {
  return (
    <picture>
      <source type="image/avif" srcSet={srcSetFor("avif")} sizes="100vw" />
      <source type="image/webp" srcSet={srcSetFor("webp")} sizes="100vw" />
      <img
        src="/hero-arena-1440.webp"
        // Decorative — the <h1> names this region.
        alt=""
        // Reserves the box before bytes land, so no layout shift.
        width={1920}
        height={1083}
        decoding="async"
        // This is the LCP element, so never loading="lazy".
        fetchPriority="high"
        className={cn("absolute inset-0 size-full max-w-full object-cover object-[70%_32%]", className)}
      />
    </picture>
  );
}
