"""Archetype names, assigned by hand and committed.

Generated by explore_fit.py --emit-labels and then EDITED: the
centroids come from the model, the names come from a person. See
labeling.py for why the names are stored against centroids rather
than against cluster numbers.

Reference fit: 2025-26, whole season (all segments), k=9.

The names come from standard basketball vernacular. Seven of the nine match
role names in the Athlore archetype taxonomy
(https://athlore.app/discover/archetypes), used here as a naming vocabulary
only: it is editorial prose with no statistics or thresholds behind it, so
it could not and did not define these groups. The wording below is ours.

Three of the nine were judgement calls worth recording:

  - "Catch-and-shoot wing" is the group most people would call a 3-and-D
    wing, and these players mostly are that. It is NOT named so here
    because a three-point attempt rate of 0.67 is measured and the "D" is
    not: point-of-attack defence produces no box-score event when it
    works, so naming the cluster after it would claim something the
    feature set cannot see.
  - "Defensive guard" DOES claim a defensive skill, and deliberately, on
    the strength of a measurement rather than a reputation: this group
    steals 2.48 per 36 minutes against a league spread of 1.04 to 1.62,
    while carrying the lowest usage of any cluster. That is ball-hawking
    specifically, not defence in general, and the README says so. It is
    the one defensive claim in this file the data supports.
  - "Low-usage forward" is invented. No vernacular name covers it, which is
    itself expected: curated taxonomies are built around the players people
    write about, and the league's largest group is the one nobody writes
    about. The name describes only what separates them from the
    catch-and-shoot wings above - similar usage, but far fewer threes.

"Combo guard" was used in an earlier fit and has been retired. It sat
between the pass-first and scoring guard clusters without ever owning a
region of its own, which is what the taxonomy's own framing predicts for
it. Three Athlore names are unused: "midrange specialist" needs each zone's
share of points and "defensive anchor" needs real defensive measurement,
neither of which is ingested.

Re-generating this file discards the names. To re-fit while keeping
them, leave this file alone — labeling.assign_archetype_names matches
the new clusters to these centroids.
"""

ARCHETYPE_LABELS = [
    {
        # 20 players. Closest: Alperen Sengun, Paolo Banchero, Julius Randle, LeBron James.
        "name": "Point forward",
        "reference_centroid": [24.2238, 2.3794, 7.5453, 5.8125, 1.2179, 0.9779, 3.1631, 3.6804, 0.2128, 0.4116, 0.5966, 1.8427, 26.4566, 81.8000, 249.4500],
    },
    {
        # 12 players. Closest: Kris Dunn, Cason Wallace, Bez Mbeng, Alex Caruso.
        "name": "Defensive guard",
        "reference_centroid": [12.0039, 2.0504, 4.4740, 4.6513, 2.4803, 0.7908, 1.7481, 3.8814, 0.3934, 0.1940, 0.5570, 2.6861, 13.8894, 76.0833, 199.4167],
    },
    {
        # 50 players. Closest: Devin Vassell, Harrison Barnes, Vít Krejčí, Svi Mykhailiuk.
        "name": "Catch-and-shoot wing",
        "reference_centroid": [14.3018, 1.0355, 3.6429, 2.8495, 1.0686, 0.3940, 1.2451, 7.5448, 0.6701, 0.1618, 0.5936, 2.3696, 14.8430, 77.6600, 208.5800],
    },
    {
        # 30 players. Closest: Keyonte George, Donovan Mitchell, James Harden, Devin Booker.
        "name": "Scoring guard",
        "reference_centroid": [26.1479, 0.8058, 4.6004, 7.0544, 1.3889, 0.4036, 3.3973, 7.8099, 0.4009, 0.3393, 0.5868, 2.0964, 28.9212, 76.3333, 201.3667],
    },
    {
        # 66 players. Closest: Desmond Bane, Kyle Kuzma, RJ Barrett, Cedric Coward.
        "name": "Scoring wing",
        "reference_centroid": [19.9675, 1.2871, 4.3557, 3.6676, 1.1295, 0.4957, 2.2012, 6.5192, 0.4190, 0.2628, 0.5802, 1.7027, 21.7653, 78.3030, 209.8182],
    },
    {
        # 36 players. Closest: Neemias Queta, Marvin Bagley III, Mark Williams, Jakob Poeltl.
        "name": "Traditional big",
        "reference_centroid": [14.7101, 4.5858, 7.1617, 2.4958, 1.0951, 1.6820, 1.9201, 0.8178, 0.0765, 0.3926, 0.6530, 1.3785, 14.7812, 83.0278, 246.5833],
    },
    {
        # 34 players. Closest: Onyeka Okongwu, Santi Aldama, Sandro Mamukelashvili, Jabari Smith Jr..
        "name": "Stretch big",
        "reference_centroid": [18.3850, 2.2014, 6.8583, 2.8486, 1.0426, 1.3151, 1.8473, 6.1386, 0.4435, 0.2447, 0.5870, 1.5694, 19.6409, 82.2059, 238.6176],
    },
    {
        # 41 players. Closest: De'Aaron Fox, Pat Spencer, Javon Small, Walter Clayton Jr..
        "name": "Pass-first point guard",
        "reference_centroid": [16.6637, 0.9119, 3.7356, 6.7315, 1.4940, 0.4024, 2.5595, 6.0507, 0.4465, 0.2140, 0.5518, 2.7712, 19.8430, 74.8293, 193.0732],
    },
    {
        # 42 players. Closest: Jamir Watkins, Zaccharie Risacher, Ryan Dunn, Jake LaRavia.
        "name": "Low-usage forward",
        "reference_centroid": [12.5789, 1.7395, 4.2919, 2.5185, 1.6156, 0.7500, 1.6168, 4.8449, 0.4626, 0.2175, 0.5477, 1.5683, 14.7060, 78.5714, 208.1429],
    },
]
